name: Docker Image CI

on:
  #push:
  #  branches: [ "master" ]
  workflows_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for the test
      run: docker build . --file Dockerfile --tag redundans:$(date +%s)
